FROM adoptopenjdk/openjdk11:jre-11.0.6_10-alpine
VOLUME /tmp
COPY apiEncryptionKey.jks apiEncryptionKey.jks
COPY UnlimitedJCEPolicyJDK8/* /usr/lib/jvm/java-11-openjdk-11.0.9.11-0.amzn2.0.1.x86_64/jre/lib/security/
COPY target/PixappConfigServer-0.0.1-SNAPSHOT.jar ConfigServer.jar
# ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","ConfigServer.jar"]
ENTRYPOINT ["java","-jar","ConfigServer.jar"]